name: "Secret Scanning"

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "docs/**"  # Ignore changes in the 'docs' folder
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "docs/**"  # Ignore changes in the 'docs' folder

jobs:
  secret_scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # GitHub's built-in secret scanning
      - name: Secret Scanning
        run: echo "Run GitHub's built-in secret scanning"
